### ISSUE TITLE
Container stop/removing immediately after create, How to stop that?

### ISSUE THREAD

**Issue by zaahmed-nisum-com** [hoverkraft-tech/compose-action#24]
name: Create docker image

on: 
  push:
    branches:
      - action-for-docker-compose

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "docker-compose.yml"
   

tried with 
        up-flags: --build
          down-flags: --volumes
 these tags also

**Comment by lhtvineettiwari** [comment]
@zaahmed-nisum-com have you find any solution for this one ??

**Comment by JPaulMora** [comment]
Same issue here, I want my docker containers to stay up
