### ISSUE TITLE
Run Scripts after docker starts

### ISSUE THREAD

**Issue by harshraj22** [hoverkraft-tech/compose-action#27]
Once docker containers start, can we run a few scripts before it goes down ?

For eg, my project has microservices orchestrated by docker-compose. I would like to run an integration test script after all services have been started in the github actions. How to do that ?

**Comment by adambirds** [comment]
This would be great to know.

**Comment by adambirds** [comment]
@harshraj22 i forked it and added this feature - https://github.com/adambirds/compose-action

**Comment by harshraj22** [comment]
@adambirds this seems to fail, not sure why:
actions job run link: https://github.com/harshraj22/smallProjects/actions/runs/4645464592/jobs/8221308984
Repo Link: https://github.com/harshraj22/smallProjects/blob/master/.github/workflows/main.yml

**Comment by adambirds** [comment]
@harshraj22 you need to specify "test-container" as well to tell it which container to run the tests in! If still an issue raise an issue in my repo and I'll look into it further!

**Comment by harshraj22** [comment]
@adambirds So if I have 5 microservices(a,b,c,d,e) and I want to run load/ integration tests, should I specify `test-container` as one of these ? or any other random ones like `ubuntu` etc would work ?

**Comment by adambirds** [comment]
@harshraj22 so I've fixed the first error you got but currently it only supports running tests in one container. For now just create multiple jobs so you can run on multiple. I will try to add the ability for it to work with multiple, but if you can raise an issue for that here:

https://github.com/adambirds/docker-compose-action/issues

For now, use the latest version by doing:

```yaml
- name: Docker Compose with Tests Action
  uses: adambirds/docker-compose-action@v1.1.0
```
