### ISSUE TITLE
Current Working Directory

### ISSUE THREAD

**Issue by visch** [hoverkraft-tech/compose-action#29]
I have a case where I'm trying to use a docker-compose file in a different directory, and the compose file has relative folder paths. 

See https://github.com/MeltanoLabs/tap-postgres/blob/ssh_tunnel/ssh_tunnel/docker-compose.yml#L16 

Ideally this action would support the `cwd` field here https://github.com/isbang/compose-action/blob/main/node_modules/docker-compose/src/index.ts#L6

**Comment by visch** [comment]
Wow, thank you @neilime great work :D

**Comment by neilime** [comment]
Available in new release: https://github.com/hoverkraft-tech/compose-action/releases/tag/v2.0.0
