### ISSUE TITLE
Feature request: container logs on cleanup

### ISSUE THREAD

**Issue by beanow-at-crabnebula** [hoverkraft-tech/compose-action#36]
A feature that would be great to replicate from Github's [service containers](https://docs.github.com/en/actions/using-containerized-services/about-service-containers) is to output container logs as part of the "post" step.

Since this isn't available as a `docker compose down` option, it would need to be an additional call by the action.

**Comment by aaletov** [comment]
I agree that this would be useful. @beanow-at-crabnebula did you come up with some workaround while this is not implemented?

**Comment by neilime** [comment]
Available in new release: https://github.com/hoverkraft-tech/compose-action/releases/tag/v2.0.0
