### ISSUE TITLE
Node 16 deprecated for actions

### ISSUE THREAD

**Issue by danharten-sovtech** [hoverkraft-tech/compose-action#38]
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: isbang/compose-action@v1.5.1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by thorrak** [comment]
I believe this is covered by PR #37

**Comment by neilime** [comment]
Fixed by https://github.com/hoverkraft-tech/compose-action/pull/56

**Comment by andrew-secret** [comment]
@danharten-sovtech yea we just need to wait for a new release 🙌🏻

**Comment by neilime** [comment]
Here is the new release: https://github.com/hoverkraft-tech/compose-action/releases/tag/v2.0.0
