### ISSUE TITLE
What's the point of this action when GitHub runners already support docker compose natively?

### ISSUE THREAD

**Issue by RichardJECooke** [hoverkraft-tech/compose-action#39]
What's the point of this action when GitHub runners already support docker compose natively?

**Comment by KrzysztofDzioba** [comment]
Can you drop full example of native usage?

**Comment by RichardJECooke** [comment]
I got docker compose to work fine without any plugins - https://github.com/mordavia/fusionauth_github_marketplace_action/blob/main/action.yaml

**Comment by neilime** [comment]
This action does not provides docker-compose. It make it usage easier, by managing setup & cleanup out of the box
