### ISSUE TITLE
Seeking Project Managers

### ISSUE THREAD

**Issue by isbang** [hoverkraft-tech/compose-action#40]
Hello contributors and potential contributors,

I am sincerely grateful for the many users who have been using compose-action. However, I must admit that I have not been able to properly manage it over the past six months, and I anticipate it will continue to be challenging for me in the future. Therefore, **I am seeking users or groups who can take over the management of this project.**

This project originated from an observation at my previous company where many engineers were omitting `docker-compose down` in their CI processes. To prevent this mistake, I initiated this project. However, I am now working at a new company which is using [Testcontainers](https://testcontainers.com/) in CI, making it difficult for me to continue focusing on this project.

I will review and address all existing issues and pull requests by March.

If you are interested, please let me know through this issue by March 31st.

cc @ricglz @thorrak @neilime @mkoehnke @9bany @gghcode @rpede @OldSneerJaw @razvanz @pauloconnor @alexkainzinger

**Comment by neilime** [comment]
Hi @isbang, Me and my teammate  will be able to take over the management, but for commodité and efficiency we will need to transfer the ownership to our open source organization: https://github.com/hoverkraft-tech

Let us know if it's could be a solution for you.

**Comment by isbang** [comment]
Hi @neilime, thank you for the suggestion. It seems like there are no other proposals, so I'll hand over this project to your team. I'm willing to transfer the project if necessary, but please promise to keep this project as an open-source.

**Comment by neilime** [comment]
@isbang you can count on me, all the open source projects we are managing with Hoverkraft-tech will remain open source.

**Comment by isbang** [comment]
You and your team has ownership now. Thank you to keep this project going
