### ISSUE TITLE
Repository not found

### ISSUE THREAD

**Issue by mstrong-tech** [hoverkraft-tech/compose-action#42]
`uses: isbang/compose-action@v1.5.1`

![image](https://github.com/hoverkraft-tech/compose-action/assets/59189994/4ed80cf4-01af-4628-b815-c9b69a9dd817)

**Comment by jameshounshell** [comment]
The org changed twice quite quickly, replace the invocation with this:
`uses: hoverkraft-tech/compose-action@main`

**Comment by jameshounshell** [comment]
@isbang @neilime 
Just a heads up, github is not honoring redirects to your action during these repo/org name changes.

**Comment by neilime** [comment]
That's bad that GitHub dos not support this out of the box, and we didn't find out a solution to handle that change (yet we have use the transfer ownership feature)

**Comment by isbang** [comment]
Please tell me any thing if I can help

**Comment by heatlikeheatwave** [comment]
Came here to upvote this issue. I've made the change to `hoverkraft-tech/compose-action`, but I am still getting `Error: Unable to resolve action. Repository not found: isbang/compose-action`

**Comment by isbang** [comment]
Is it possible to release the 1.5.1 version again? I am not sure, but maybe it can solve this problem.

**Comment by neilime** [comment]
@isbang it does not work either

**Comment by neilime** [comment]
FYI a new major release is available: https://github.com/hoverkraft-tech/compose-action/releases/tag/v2.0.0
